version: "2.2"

services:
  es8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: es8
    environment:
      - node.name=es08
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false

    volumes:
      - esdata8:/usr/share/elasticsearch/data

    ports:
      - 9200:9200

    networks:
      - elastic

  kibana8:
    depends_on:
      - es8
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana8
    environment:
      - node.name=kibana08
      - cluster.name=es-docker-cluster
      - ELASTICSEARCH_HOSTS=http://es8:9200

    ports:
      - 5601:5601

    networks:
      - elastic

volumes:
  esdata8:
    driver: local

networks:
  elastic:
    driver: bridge
